### ISSUE TITLE
As a job seeker in an underserved population who has limited access to the internet register for career evaluation so that I may receive information that helps me prioritize my job search based on workforce development focused industries.

### ISSUE THREAD

**Issue by tungly** [loyno-mathcs/workforwardnola#1]
As a job seeker in an underserved population who has limited access to the internet register for career evaluation so that I may receive information that helps me prioritize my job search based on workforce development focused industries.
[CFA questions (1).xlsx](https://github.com/loyno-mathcs/workforwardnola/files/1285498/CFA.questions.1.xlsx)

**Comment by nihonjinrxs** [comment]
General umbrella issue.
