### ISSUE TITLE
Use communication template for issue/concern/blocker updates (0)

### ISSUE THREAD

**Issue by maahern** [loyno-mathcs/workforwardnola#19]

**Comment by maahern** [comment]
I think some clarification is needed on this template. Many of the issues that we are running into are relatively small and are dealt with in passing/after class. Is a template like this necessary? Does anyone see a case where they would realistically use this template? @tmloupe @cam-carter @pwevans @jusantana

**Comment by tmloupe** [comment]
I feel like the template came in too late into the lifespan of the project. Now that we have other additional forms of communication, and much more direct as well, I think it's not as useful and I probably won't use it unless I happen to need to write something down before I forget it.

**Comment by maahern** [comment]
Okay, it might make sense to put this issue aside for now at it seems we don't have any use cases for this template. It sounds like there is a consensus on this matter... I will close this issue.
