### ISSUE TITLE
As a prospective client of Opportunity Centers receive immediate contact via follow up from email notification by the agency recommended by job readiness and barrier/need criteria.

### ISSUE THREAD

**Issue by tungly** [loyno-mathcs/workforwardnola#2]
As a prospective client of Opportunity Centers receive immediate contact via follow up from email notification by the agency recommended by job readiness and barrier/need criteria.
[OC Matrix with contacts (1).xlsx](https://github.com/loyno-mathcs/workforwardnola/files/1285503/OC.Matrix.with.contacts.1.xlsx)

**Comment by nihonjinrxs** [comment]
Human process issue for Opportunity Centers.
