### ISSUE TITLE
User experience for career selection (2)

### ISSUE THREAD

**Issue by nihonjinrxs** [loyno-mathcs/workforwardnola#6]
As a user considering a career path, I would like to see people who look like me as examples of that career.

**Comment by tmloupe** [comment]
@tungly @nihonjinrxs @bsabo There are not enough images included in the dropbox, considering the amount of jobs to update. Furthermore, we would like to understand where the pictures are to be located and more descriptive file names, to match them with the proper career.

**Comment by bsabo** [comment]
I will attach picture ID to jobs on the and post with more pix.

**Comment by cam-carter** [comment]
Add pictures to both results and career description // formatting already in place for results page but not for career description

**Comment by cam-carter** [comment]
Pictures without watermarks should be uploaded by 10am on 9.27.17

**Comment by tmloupe** [comment]
Here are some resources for working with Mustache and Ruby (reference for myself, but if anyone else needs to understand it)

- https://mustache.github.io/mustache.5.html
- https://github.com/mustache/mustache

**Comment by tmloupe** [comment]
Moving the discussion to here: @maahern Thanks for the clarification. I'm using a separate spreadsheet to only test file_name and alt_title. I will take a look at the issues on my end.

**Comment by tmloupe** [comment]
Issue complete, successfully merged into master and approved. Closing.
