### ISSUE TITLE
Include info on certification and training (1)

### ISSUE THREAD

**Issue by nihonjinrxs** [loyno-mathcs/workforwardnola#8]
As a user, I would like to get information about any certification requirements and available training, so that I can be prepared to begin my career path.

**Comment by cam-carter** [comment]
certification & training // Add new row to results columns that displays certification & training required

**Comment by nihonjinrxs** [comment]
Per planning session, customer will provide one link to a site with training information.

**Comment by cam-carter** [comment]
@bsabo @nihonjinrxs Added the placeholder for the link, but I need the actual link.  I may be missing it somewhere in the shared files, but if you could provide it or point me to it that would be great!

**Comment by nihonjinrxs** [comment]
I think this is the link you're looking for.  Note that the misspelling is actually in the link.
@bsabo correct me if that's wrong place to link to for training info.
https://careerpathnola.business/training-and-educucation

**Comment by cam-carter** [comment]
@nihonjinrxs Awesome! Thanks so much.

**Comment by bsabo** [comment]
I will fix the spelling right now.

**Comment by tmloupe** [comment]
Completed and merged into master.
